PREFIX uniprot: <http://purl.uniprot.org/core/>
CONSTRUCT {
	?uniprot_uri rdfs:seeAlso ?ipi_uri
} WHERE {
	GRAPH <http://purl.uniprot.org> {
		?uniprot_uri rdfs:seeAlso ?ipi_uri .
		?ipi_uri uniprot:database <http://purl.uniprot.org/database/IPI> .
	}
}
