PREFIX uniprot: <http://purl.uniprot.org/core/>
CONSTRUCT {
	?uniprot_uri rdfs:seeAlso ?flybase_uri
} WHERE {
	GRAPH <http://purl.uniprot.org> {
		?uniprot_uri <http://semanticscience.org/resource/SIO_010043> ?flybase_uri .
		?flybase_uri uniprot:database <http://purl.uniprot.org/database/FlyBase> .
	}
}
