PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {
	?uniprot_uri rdfs:seeAlso ?ensembl_uri
} WHERE {
	GRAPH <http://purl.uniprot.org> {
		?uniprot_uri rdfs:seeAlso ?ensembl_uri .
		?ensembl_uri uniprot:database <http://purl.uniprot.org/database/Ensembl> .
    }
}
