PREFIX uniprot: <http://purl.uniprot.org/core/>
CONSTRUCT {
	?uniprot_uri rdfs:seeAlso ?zfin_uri
} WHERE {
	GRAPH <http://purl.uniprot.org> {
		?uniprot_uri rdfs:seeAlso ?zfin_uri .
		?zfin_uri uniprot:database <http://purl.uniprot.org/database/ZFIN> .
	}
}
